;; Any site-wide Festival initialization can be added to this file.
;; It is marked as a configuration file, so your changes will be saved
;; across upgrades of the Festival package.
;(Parameter.set 'Audio_Method 'Audio_Command)
;(Parameter.set 'Audio_Required_Format 'wav)
;(Parameter.set 'Audio_Command "play $FILE")
;(load "/usr/share/mbrola/cz2_mbrola.scm")
;(load "/mnt/data/festival/voices/czech/mik_diphone/festvox/mik_diphone.scm")
;; default voice
(set! voice_default 'voice_czech_ph)
;; For czech mbrola
(set! server_access_list '("127.0.0.1" "localhost" ))
(set! server_log_file "/tmp/festival-server.log")
(set_backtrace t)
(set! load-path (cons "/usr/local/share/festival-czech" load-path))
(set! mbrola_progname "/usr/share/mbrola/mbrola")
(set! czech-mbrola_database "/usr/share/mbrola/cz2/cz2")
(set! czech-randomize nil)
(require 'czech)
(require 'czech-unisyn)
(require 'nopauses)
(set! inhibit-initial-pauses t)

;; For german mbrola
; (set! load-path (cons "/usr/local/share/festival/festival-german" load-path))
; (set! german-mbrola_database "/usr/share/mbrola/de3/de3")
; (require 'german)
; (require 'german-mbrola)
; (set! german-description german-mbrola-description)
; (set! german-unknown-symbol-word "")
; (voice_german)

(set! logical-event-mapping
  '((capital sound "capital")
    (empty-text sound "empty-text")
    (start sound "start")
    (door sound "door")
    (posta sound "posta")    
    (prompt sound "prompt")
    (message sound "message")
    (finish sound "finish")
    (checht sound "checht")
    (prachy sound "prachy")

    (beginning-of-line sound "beginning-of-line")
    (end-of-line sound "end-of-line")))

(set! word-mapping
      '(("(" sound "left-round-bracket")
	(")" sound "right-round-bracket")
	("[" sound "left-square-bracket")
	("]" sound "right-square-bracket")
	("{" sound "left-brace")
	("}" sound "right-brace")
	(":-)" sound "checht")
					;    ("<" sound "left-angle-bracket")
					;    (">" sound "right-angle-bracket")
	("°" text "stupeò")
	("°CC" text "stupòù celsia")
	("|" sound "pipe")
	("#" sound "hash")))

(set! key-event-mapping
      '(("(" sound "left-round-bracket")
	(")" sound "right-round-bracket")
	("[" sound "left-square-bracket")
	("]" sound "right-square-bracket")
	("{" sound "left-brace")
	("}" sound "right-brace")
					;    ("<" sound "left-angle-bracket")
					;    (">" sound "right-angle-bracket")
	("|" sound "pipe")
	("#" sound "hash")
	("@" sound "at")
	("$" sound "prachy")
					;	("." sound "dot")
					;	("," sound "coma")
	("#" sound "hash")
	("|" sound "pipe")
					;	("$" sound "dolar")
	("control_m" text "enter")
	("control_[" text "escape")
	("control_i" text "tab")
	("shift_a" key "A")
	("shift_á" key "Á")
	("shift_b" key "B")
	("shift_c" key "C")
	("shift_è" key "È")
	("shift_d" key "D")
	("shift_ï" key "Ï")
	("shift_e" key "E")
	("shift_é" key "É")
	("shift_ì" key "Ì")
	("shift_f" key "F")
	("shift_g" key "G")
	("shift_h" key "H")
	("shift_i" key "I")
	("shift_í" key "Í")
	("shift_j" key "J")
	("shift_k" key "K")
	("shift_l" key "L")
	("shift_m" key "M")
	("shift_n" key "N")
	("shift_ò" key "Ò")
	("shift_o" key "O")
	("shift_ó" key "Ó")
	("shift_p" key "P")
	("shift_q" key "Q")
	("shift_r" key "R")
	("shift_ø" key "Ø")
	("shift_s" key "S")
	("shift_¹" key "©")
	("shift_t" key "T")
	("shift_»" key "«")
	("shift_u" key "U")
	("shift_ú" key "Ú")
	("shift_ù" key "Ù")
	("shift_v" key "V")
	("shift_w" key "W")
	("shift_x" key "X")
	("shift_y" key "Y")
	("shift_ý" key "Ý")
	("shift_z" key "Z")
	("shift_¾" key "®")
	("f1" text "f 1")
	("f2" text "f 2")
	("f3" text "f 3")
	("f4" text "f 4")
	("f5" text "f 5")
	("f6" text "f 6")
	("f7" text "f 7")
	("f8" text "f 8")
	("f9" text "f 9")
	("f10" text "f 10")
	("f11" text "f 11")
	("f12" text "f 12")))

(set! character-event-mapping
      '(("(" text "leftroundbracket")
	(")" text "rightroundbracket")
	("[" text "leftsquarebracket")
	("]" text "rightsquarebracket")
	("{" text "leftbrace")
	("}" text "rightbrace")
					;    ("<" sound "left-angle-bracket")
					;    (">" sound "right-angle-bracket")
	("|" sound "pipe")
	("#" sound "hash")
	("@" sound "at")
					;	("." sound "dot")
					;	("," sound "coma")
	("#" sound "hash")
	("|" sound "pipe")
					;	("$" sound "dolar")
	("|" sound "pipe")	
	("control_m" text "enter")
	("control_[" text "escape")
	("control_i" text "tab")
	("shift_a" key "A")
	("shift_á" key "Á")
	("shift_b" key "B")
	("shift_c" key "C")
	("shift_è" key "È")
	("shift_d" key "D")
	("shift_ï" key "Ï")
	("shift_e" key "E")
	("shift_é" key "É")
	("shift_ì" key "Ì")
	("shift_f" key "F")
	("shift_g" key "G")
	("shift_h" key "H")
	("shift_i" key "I")
	("shift_í" key "Í")
	("shift_j" key "J")
	("shift_k" key "K")
	("shift_l" key "L")
	("shift_m" key "M")
	("shift_n" key "N")
	("shift_ò" key "Ò")
	("shift_o" key "O")
	("shift_ó" key "Ó")
	("shift_p" key "P")
	("shift_q" key "Q")
	("shift_r" key "R")
	("shift_ø" key "Ø")
	("shift_s" key "S")
	("shift_¹" key "©")
	("shift_t" key "T")
	("shift_»" key "«")
	("shift_u" key "U")
	("shift_ú" key "Ú")
	("shift_ù" key "Ù")
	("shift_v" key "V")
	("shift_w" key "W")
	("shift_x" key "X")
	("shift_y" key "Y")
	("shift_ý" key "Ý")
	("shift_z" key "Z")
	("shift_¾" key "®")
	(" " text "mezera")
	("f1" text "f 1")
	("f2" text "f 2")
	("f3" text "f 3")
	("f4" text "f 4")
	("f5" text "f 5")
	("f6" text "f 6")
	("f7" text "f 7")
	("f8" text "f 8")
	("f9" text "f 9")
	("f10" text "f 10")
	("f11" text "f 11")
	("f12" text "f 12")))


;(define (insert_initial_pause utt))
;(define (insert_pause utt))
(require 'speech-dispatcher)
(require 'voice-select)
(set! language-codes (cons '(hi hindi) language-codes))
